n1 = int(input('Uma distância em metros: '))
print('A medida de {}m corresponde a: '.format(n1))
print('{}km'.format(n1/1000))
print('{}hm'.format(n1/100))
print('{}dam'.format(n1/10))
print('{}dm'.format(n1*10))
print('{}cm'.format(n1*100))
print('{}mm'.format(n1*1000))