nome = input("Nome: ")
idade = int(input("Idade: "))
banco = input("Banco: ")
saldo = float(input("Saldo: R$"))
print("Nome: " + nome)
print("Idade: " + idade)
print("Banco: " + banco)
print("Saldo: " + saldo)